/**
 * Corpus do classificador de Conteúdo Clínico (ADR-0004, ADR-0012).
 *
 * Frases como chegam pelo WhatsApp de uma clínica de bairro. O que está em
 * `CLINICOS` revela sintoma, condição ou medicação e NUNCA pode ser gravado.
 * O que está em `NAO_CLINICOS` é escolha, logística ou conversa — inclusive o
 * nome de uma especialidade, que é o que o Contato ESCOLHE, não o que revela.
 * `AMBIGUOS` são falsos positivos aceitos de olhos abertos: ficam fora das
 * asserções para o léxico não afrouxar por causa deles.
 */
export const CLINICOS: readonly string[] = [
  "tô com dor de cabeça há 3 dias",
  "minha filha está com febre desde ontem",
  "estou com dor no peito",
  "sinto uma dor nas costas que não passa",
  "tô com muita tosse e falta de ar",
  "estou com enjoo e vômito",
  "meu filho tá com diarreia",
  "acordei com o olho inchado e vermelho",
  "tô com uma coceira no corpo todo",
  "meu joelho está inchado",
  "sinto tontura quando levanto",
  "estou com dor de garganta forte",
  "minha pressão tá alta",
  "estou com dor ao urinar",
  "tô com a barriga inchada e dor",
  "tenho diabetes e preciso de acompanhamento",
  "sou hipertensa",
  "tenho asma desde criança",
  "fui diagnosticada com hipotireoidismo",
  "tenho ansiedade e crises de pânico",
  "estou com depressão",
  "tenho gastrite",
  "minha mãe tem alzheimer",
  "tive uma infecção urinária semana passada",
  "estou grávida de 12 semanas e com sangramento",
  "tomo losartana 50mg",
  "acabou meu rivotril",
  "preciso de receita de fluoxetina",
  "estou tomando antibiótico e não melhorou",
  "posso tomar dipirona junto com o remédio da pressão",
  "tomo metformina duas vezes ao dia",
  "preciso renovar a receita do meu remédio controlado",
  "esqueci de tomar a insulina",
  "o médico passou omeprazol mas a azia continua",
  "tomo 2 comprimidos de 500mg por dia",
  "pode me dizer se isso é grave",
  "tô com suspeita de dengue",
  "acho que estou com covid",
  "tive uma convulsão ontem",
  "estou com sintomas de gripe",
  "minha glicose deu 300",
  "estou com uma ferida que não cicatriza",
  "a criança está com manchas vermelhas na pele",
];

export const NAO_CLINICOS: readonly string[] = [
  "quero marcar com a cardiologista",
  "tem vaga na psiquiatria essa semana?",
  "quanto custa a consulta de nutrição",
  "queria agendar pediatria pra minha filha",
  "vocês têm ginecologista à tarde?",
  "quero marcar ortopedia",
  "tem psicólogo que atende sábado?",
  "gostaria de marcar uma consulta com clínico geral",
  "quero fazer pilates aí",
  "tem aula de hidroginástica de manhã?",
  "quero marcar fisioterapia",
  "qual o endereço da clínica",
  "vocês aceitam unimed?",
  "aceita cartão de crédito?",
  "posso remarcar pra terça?",
  "preciso cancelar minha consulta de amanhã",
  "que horas vocês abrem?",
  "tem estacionamento?",
  "bom dia",
  "oi, tudo bem?",
  "obrigada!",
  "ok, confirmado",
  "vou chegar 10 minutos atrasado",
  "qual o valor do exame de sangue?",
  "vocês fazem exame de rotina?",
  "quero fazer um check-up",
  "preciso de um atestado de comparecimento",
  "posso levar acompanhante?",
  "a doutora rafaela atende hoje?",
  "quero marcar com a dra rafaela",
  "consulta de retorno é cobrada?",
  "como faço pra pegar o resultado do exame",
  "vocês atendem criança?",
  "tem dentista aí?",
  "qual o telefone da recepção",
  "vou de ônibus, qual a linha que passa aí",
  "posso pagar no pix?",
  "quero saber os horários da dança",
  "tem convênio com o bradesco saúde?",
  "queria uma segunda via do recibo",
  "quero marcar cirurgia geral, é só avaliação",
  "primeira consulta de cardiologia, quanto custa?",
];

/** Falsos positivos que aceitamos: melhor um humano ler do que o banco guardar. */
export const AMBIGUOS: readonly string[] = [
  "a dor de cabeça é ver o trânsito daí",
  "meu carro tá com febre de tanto rodar",
];
